import 'dart:io';
import 'plant_profile.dart';

/// Holds all data collected during the plant onboarding wizard
class PlantOnboardingData {
  // Step 1: Photo capture (optional)
  File? capturedImage;
  String? imageBase64;
  
  // From AI analysis
  String? plantId;          // Generated by backend if photo taken
  int? capturedAt;
  String? imageUrl;
  OnboardingSuggestions? suggestions;
  HealthAssessment? healthAssessment;
  bool needsSpeciesSelection = true;
  
  // Step 2: Plant details (user confirms/edits)
  String nickname = '';
  String? species;
  String? commonName;
  String emoji = '🪴';
  PlantProfile? selectedProfile;
  bool isCustomSpecies = false;
  
  // Step 3: Pot measurements
  double? potHeightInches;
  double? potWidthInches;
  double? potVolumeML;
  double? plantHeightInches;
  String measurementMethod = 'manual'; // 'manual' or 'camera'
  
  // Step 4: Light measurement
  double? measuredLux;
  String? lightCategory;
  
  // Step 5: Location & device
  String? room;
  String? windowProximity;
  String? esp32DeviceId;
  String environment = 'indoor'; // 'indoor' or 'outdoor'
  
  PlantOnboardingData();
  
  /// Create from AI analysis response
  factory PlantOnboardingData.fromAnalysis(Map<String, dynamic> response) {
    final data = PlantOnboardingData();
    
    data.plantId = response['plantId'];
    data.capturedAt = response['capturedAt'];
    data.imageUrl = response['imageUrl'];
    data.needsSpeciesSelection = response['needsSpeciesSelection'] ?? true;
    
    if (response['suggestions'] != null) {
      data.suggestions = OnboardingSuggestions.fromJson(response['suggestions']);
      
      // Pre-fill from suggestions
      data.species = data.suggestions!.species;
      data.commonName = data.suggestions!.commonName;
      data.nickname = data.suggestions!.nickname ?? data.commonName ?? 'My Plant';
      data.emoji = data.suggestions!.emoji ?? '🪴';
      data.environment = data.suggestions!.environment ?? 'indoor';
      data.needsSpeciesSelection = !data.suggestions!.isIdentified;
    }
    
    if (response['healthAssessment'] != null) {
      data.healthAssessment = HealthAssessment.fromJson(response['healthAssessment']);
      
      // Pre-fill height if estimated
      if (data.healthAssessment!.estimatedHeightCm != null) {
        data.plantHeightInches = data.healthAssessment!.estimatedHeightCm! / 2.54;
      }
    }
    
    return data;
  }
  
  /// Check if we have enough data to save
  bool get canSave {
    return nickname.trim().isNotEmpty && 
           (species != null && species!.isNotEmpty);
  }
  
  /// Build the environment map for API
  Map<String, dynamic>? buildEnvironment() {
    final location = <String, dynamic>{};
    
    if (room != null) location['room'] = room;
    if (windowProximity != null) location['windowProximity'] = windowProximity;
    if (measuredLux != null) location['luxLevel'] = measuredLux;
    
    if (location.isEmpty && environment == 'indoor') {
      return null;
    }
    
    return {
      'type': environment,
      if (location.isNotEmpty) 'location': location,
    };
  }
  
  /// Build measurements map for API
  Map<String, dynamic>? buildMeasurements() {
    if (potHeightInches == null && potWidthInches == null && plantHeightInches == null) {
      return null;
    }
    
    return {
      if (potHeightInches != null) 'potHeightInches': potHeightInches,
      if (potWidthInches != null) 'potWidthInches': potWidthInches,
      if (potVolumeML != null) 'potVolumeML': potVolumeML,
      if (plantHeightInches != null) 'plantHeightInches': plantHeightInches,
      'measurementMethod': measurementMethod,
      'measuredAt': DateTime.now().toIso8601String(),
    };
  }
  
  /// Build speciesInfo map for API
  Map<String, dynamic>? buildSpeciesInfo() {
    if (selectedProfile != null && !isCustomSpecies) {
      return {
        'commonName': selectedProfile!.commonName,
        'scientificName': selectedProfile!.species,
        'emoji': selectedProfile!.emoji,
        if (selectedProfile!.careProfile != null) ...{
          'waterFrequencyDays': selectedProfile!.careProfile!.watering.frequencyDays,
          'waterAmountML': selectedProfile!.careProfile!.watering.amountML,
          'lightRequirement': selectedProfile!.careProfile!.light.type,
          'careProfile': {
            'watering': {
              'frequencyDays': selectedProfile!.careProfile!.watering.frequencyDays,
              'amountML': selectedProfile!.careProfile!.watering.amountML,
            },
            'light': {
              'type': selectedProfile!.careProfile!.light.type,
              'minLux': selectedProfile!.careProfile!.light.minLux,
            },
          },
        },
      };
    }
    
    // For AI-identified or custom species
    if (suggestions != null && !isCustomSpecies) {
      return {
        'commonName': commonName ?? suggestions!.commonName,
        'scientificName': species ?? suggestions!.species,
        'emoji': emoji,
        if (suggestions!.lightPreference != null)
          'lightRequirement': suggestions!.lightPreference,
        if (suggestions!.careLevel != null)
          'careLevel': suggestions!.careLevel,
      };
    }
    
    return null;
  }
}

/// AI-suggested plant information
class OnboardingSuggestions {
  final String? species;
  final String? commonName;
  final String? genus;
  final String? family;
  final double confidence;
  final bool isIdentified;
  final List<AlternativeMatch> alternativeMatches;
  
  final String? nickname;
  final String? emoji;
  final int? potSizeMl;
  final String? environment;
  
  final String? plantType;
  final String? careLevel;
  final String? lightPreference;
  final String? wateringNeeds;
  final bool? petSafe;
  final String? description;
  
  OnboardingSuggestions({
    this.species,
    this.commonName,
    this.genus,
    this.family,
    this.confidence = 0.0,
    this.isIdentified = false,
    this.alternativeMatches = const [],
    this.nickname,
    this.emoji,
    this.potSizeMl,
    this.environment,
    this.plantType,
    this.careLevel,
    this.lightPreference,
    this.wateringNeeds,
    this.petSafe,
    this.description,
  });
  
  factory OnboardingSuggestions.fromJson(Map<String, dynamic> json) {
    return OnboardingSuggestions(
      species: json['species'],
      commonName: json['commonName'],
      genus: json['genus'],
      family: json['family'],
      confidence: (json['confidence'] as num?)?.toDouble() ?? 0.0,
      isIdentified: json['isIdentified'] ?? false,
      alternativeMatches: (json['alternativeMatches'] as List?)
          ?.map((e) => AlternativeMatch.fromJson(e))
          .toList() ?? [],
      nickname: json['nickname'],
      emoji: json['emoji'],
      potSizeMl: json['potSizeMl'],
      environment: json['environment'],
      plantType: json['plantType'],
      careLevel: json['careLevel'],
      lightPreference: json['lightPreference'],
      wateringNeeds: json['wateringNeeds'],
      petSafe: json['petSafe'],
      description: json['description'],
    );
  }
}

class AlternativeMatch {
  final String species;
  final String commonName;
  final double confidence;
  
  AlternativeMatch({
    required this.species,
    required this.commonName,
    required this.confidence,
  });
  
  factory AlternativeMatch.fromJson(Map<String, dynamic> json) {
    return AlternativeMatch(
      species: json['species'] ?? '',
      commonName: json['commonName'] ?? '',
      confidence: (json['confidence'] as num?)?.toDouble() ?? 0.0,
    );
  }
}

class HealthAssessment {
  final double? healthScore;
  final String? healthStatus;
  final double? estimatedHeightCm;
  final String? growthStage;
  final List<String> issues;
  final List<String> recommendations;
  
  HealthAssessment({
    this.healthScore,
    this.healthStatus,
    this.estimatedHeightCm,
    this.growthStage,
    this.issues = const [],
    this.recommendations = const [],
  });
  
  factory HealthAssessment.fromJson(Map<String, dynamic> json) {
    return HealthAssessment(
      healthScore: (json['healthScore'] as num?)?.toDouble(),
      healthStatus: json['healthStatus'],
      estimatedHeightCm: (json['estimatedHeightCm'] as num?)?.toDouble(),
      growthStage: json['growthStage'],
      issues: List<String>.from(json['issues'] ?? []),
      recommendations: List<String>.from(json['recommendations'] ?? []),
    );
  }
  
  String get healthEmoji {
    if (healthScore == null) return '❓';
    if (healthScore! >= 0.8) return '🌟';
    if (healthScore! >= 0.6) return '😊';
    if (healthScore! >= 0.4) return '😐';
    return '😟';
  }
  
  String get healthLabel {
    switch (healthStatus) {
      case 'healthy': return 'Healthy';
      case 'good': return 'Good';
      case 'warning': return 'Needs Attention';
      case 'critical': return 'Critical';
      default: return 'Unknown';
    }
  }
}